#!/bin/bash

options="install diff status"
list=(
    '.config'
    '.local'
    '.tmux.conf'
)

printUsage()
{
    echo "Usage: dot [OPTION]"
    echo "OPTIONS:"
    echo "  install [--config]"
    echo "  diff    [--config]"
    echo "  status"
}

dotStatus()
{
    flag=0
    error=0
    dotpath=$PWD

    echo "Dot status"

    # Basic Configuration File
    for dir in ${list[@]}; do
        files=`find $dir -type f`

        for file in $files; do
            if [ "$MSYSTEM" ]; then
                if [[ "$file" != *"lese"* ]]; then
                    continue
                fi
            fi

            [ ! -f "$HOME/$file" ] && echo -e "    \e[1;31mnonexistent:   $file\e[0m" && error=1 && continue
            res="`diff $file $HOME/$file`"

            if [ "$res" ]; then
                [ $flag == 0 ] && flag=1 && echo "Changes for dotfiles:"
                echo -e "\e[1;31m    modified:   $file\e[0;37m"
            fi
        done
    done

    if [ "$1" != "-a" ]; then
        [ $flag == 0 -a $error == 0 ] && echo "all same"
        return
    fi

    # Untracked Configuration File
    track=0
    cd $HOME
    if [ -d ${list[0]} ]; then
        for dir in ${list[0]}/*; do
            if [ ! -d "$dotpath/$dir" ]; then
                [ $track == 0 ] && track=1 && echo && echo "Untracked configuration:"
                echo -e "\e[1;31m    $dir\e[0;37m"
            fi
        done
    fi

    [ $flag == 0 -a $track == 0 -a $error == 0 ] && echo "all same"
}

diffFile()
{
    res="`diff $1 $2`"

    if [ "$res" ]; then
        if type diff-so-fancy >/dev/null 2>&1; then
            echo && (diff -ru $1 $2 | diff-so-fancy)
        else
            diff -ru $1 $2
        fi
    fi
}

dotDiff()
{
    echo "Dot diff"

    # Basic Configuration File
    for dir in ${list[@]}; do
        files=`find $dir -type f`

        for file in $files; do
            if [ "$MSYSTEM" ]; then
                if [[ "$file" != *"lese"* ]]; then
                    continue
                fi
            fi

            [ ! -f "$HOME/$file" ] && echo -e "    \e[1;31mnonexistent:   $file\e[0m" && continue
            diffFile $file $HOME/$file
        done
    done
}

dotInstall()
{
    echo "Dot install"

    # Basic Configuration File
    for dir in ${list[@]}; do
        if type rsync >/dev/null 2>&1; then
            rsync -av $dir $HOME
        else
            cp -rf $dir $HOME
        fi
        [ $? == 0 ] && echo "$dir install done"
    done

    echo && echo -e "Do you want to initialize the configuration? (y/n) \c" && read option
    if [ "$option" == "n" ]; then
        exit 0
    fi

    echo "" >> $HOME/.profile
    echo "source \"\$HOME/.config/lese/init.sh\" --file" >> $HOME/.profile
    echo "profile init successful"
}

if [ $# -lt 1 ]; then
    printUsage
    exit 1
fi

case $1 in
    status)
        dotStatus $2
        ;;
    diff)
        dotDiff $2
        ;;
    install)
        dotInstall $2
        ;;
    *)
        echo "error: wrong option" && echo
        printUsage
        exit 2
        ;;
esac
