#!/bin/bash

options="install diff status"
vim='.vim'
vimplugin='.config/vim/plugged'
list=(
    '.config'
    '.local'
    '.tmux.conf'
)

printUsage()
{
    echo "Usage: dot [OPTION]"
    echo "OPTIONS:"
    echo "  install"
    echo "  diff"
    echo "  status"
}

dotStatus()
{
    flag=0
    error=0
    dotpath=$PWD

    echo "Dot status"

    # Basic Configuration File
    for dir in ${list[@]}; do
        files=`find $dir -type f | grep -v "vim"`

        for file in $files; do
            [ ! -f "$HOME/$file" ] && echo -e "    \e[1;31mnonexistent:   $file\e[0m" && error=1 && continue
            res="`diff $file $HOME/$file`"

            if [ "$res" ]; then
                [ $flag == 0 ] && flag=1 && echo "Changes for dotfiles:"
                echo -e "\e[1;31m    modified:   $file\e[0;37m"
            fi
        done
    done

    # Vim Configuration File
    if [ ! -d "$HOME/$vim" ]; then
        error=1
        echo -e "    \e[1;31mnonexistent:   $vim\e[0m"
    else
        files=`find $vim -type f | grep -v "\.git"`
        for file in $files; do
            if [ ! -f "$HOME/$file" ]; then
                [ $flag == 0 ] && flag=1 && echo "Changes for dotfiles:"
                echo -e "\e[1;31m    modified:   $vim\e[0;37m" && break
            fi

            res="`diff $file $HOME/$file`"

            if [ "$res" ]; then
                [ $flag == 0 ] && flag=1 && echo "Changes for dotfiles:"
                echo -e "\e[1;31m    modified:   $vim\e[0;37m" && break
            fi
        done
    fi

    # Vim Plugin Configuration File
    for dir in $vimplugin/*; do
        if [ ! -d "$HOME/$dir" ]; then
            [ $flag == 0 ] && flag=1 && echo "Changes for dotfiles:"
            echo -e "    \e[1;31mnonexistent:   $dir\e[0m" && continue
        fi

        files=`find $dir -type f | grep -v "\.git"`
        for file in $files; do
            if [ ! -f "$HOME/$file" ]; then
                [ $flag == 0 ] && flag=1 && echo "Changes for dotfiles:"
                echo -e "\e[1;31m    modified:   $dir\e[0;37m" && break
            fi

            res="`diff $file $HOME/$file`"

            if [ "$res" ]; then
                [ $flag == 0 ] && flag=1 && echo "Changes for dotfiles:"
                echo -e "\e[1;31m    modified:   $dir\e[0;37m" && break
            fi
        done
    done

    # Untracked Configuration File
    track=0
    cd $HOME
    if [ -d ${list[0]} ]; then
        for dir in ${list[0]}/*; do
            if [ ! -d $dotpath/$dir ]; then
                [ $track == 0 ] && track=1 && echo && echo "Untracked configuration:"
                echo -e "\e[1;31m    $dir\e[0;37m"
            fi
        done
    fi

    [ $flag == 0 -a $track == 0 -a $error == 0 ] && echo "all same"
}

diffFile()
{
    res="`diff $1 $2`"

    if [ "$res" ]; then
        if type diff-so-fancy >/dev/null 2>&1; then
            echo && (diff -ru $1 $2 | diff-so-fancy)
        else
            diff -ru $1 $2
        fi
    fi
}

dotDiff()
{
    echo "Dot diff"

    # Basic Configuration File
    for dir in ${list[@]}; do
        files=`find $dir -type f | grep -v "vim"`

        for file in $files; do
            [ ! -f "$HOME/$file" ] && echo -e "    \e[1;31mnonexistent:   $file\e[0m" && continue
            diffFile $file $HOME/$file
        done
    done

    # Vim Configuration File
    if [ ! -d $HOME/$vim ]; then
        echo -e "    \e[1;31mnonexistent:   $vim\e[0m"
    else
        files=`find $vim -type f | grep -v "\.git"`
        for file in $files; do
            [ ! -f "$HOME/$file" ] && echo -e "    \e[1;31mnonexistent:   $file\e[0m" && continue
            diffFile $file $HOME/$file
        done
    fi

    # Vim Plugin Configuration File
    if [ ! -d "$HOME/$vimplugin" ]; then
        echo -e "    \e[1;31mnonexistent:   $vimplugin\e[0m"
    else
        for dir in $vimplugin/*; do
            [ ! -d "$HOME/$dir" ] && echo -e "    \e[1;31mnonexistent:   $dir\e[0m" && continue

            files=`find $dir -type f | grep -v "\.git"`
            for file in $files; do
                [ ! -f "$HOME/$file" ] && echo -e "    \e[1;31mnonexistent:   $file\e[0m" && continue
                diffFile $file $HOME/$file
            done
        done
    fi
}

dotInstall()
{
    echo "Dot install"

    # Basic Configuration File
    for dir in ${list[@]}; do
        rsync -av $dir $HOME
        [ $? == 0 ] && echo "$dir install done"
    done

    # Vim Configuration File
    rsync -av $vim $HOME
    find $HOME/$vim -name "\.git" | xargs rm -rf
    find $HOME/$vimplugin -name "\.git" | xargs rm -rf
    [ $? == 0 ] && echo "$vim install done"
}

if [ $# -ne 1 ]; then
    printUsage
    exit 1
fi

case $1 in
    status)
        dotStatus
        ;;
    diff)
        dotDiff
        ;;
    install)
        dotInstall
        ;;
    *)
        echo "error: wrong option" && echo
        printUsage
        exit 2
        ;;
esac
