# kill focused window
bindsym $mod+Shift+q kill
bindsym --whole-window $mod+button2 kill

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# scratchpad
bindsym $mod+minus move scratchpad
bindsym $mod+shift+minus scratchpad show
# wheel click
bindsym --whole-window $mod+shift+button3 move scratchpad

# Media player controls
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous

# Volume
bindsym XF86AudioMute        exec pactl set-sink-mute   @DEFAULT_SINK@ toggle
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%

# polybar toggle
bindsym $mod+x exec polybar-msg cmd toggle

# network
bindsym $mod+g exec ~/.config/polybar/scripts/network-info.sh
