# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# file manager
bindsym $mod+e exec thunar

# start rofi (a program launcher)
bindsym $mod+d exec --no-startup-id rofi -show drun   -theme /home/$USER/.config/rofi/mine.rasi
bindsym $mod+o exec --no-startup-id rofi -show window -theme /home/$USER/.config/rofi/mine.rasi
bindsym $mod+y exec --no-startup-id rofi -show clipboard -run-command '{cmd}' \
                    -modi "clipboard:greenclip print" -theme /home/$USER/.config/rofi/clip.rasi
bindsym $mod+p exec --no-startup-id /home/$USER/.local/sbin/powermenu
# scroll up
bindsym --whole-window $mod+button4 exec --no-startup-id rofi -show drun   -theme /home/$USER/.config/rofi/mine.rasi
# scroll down
bindsym --whole-window $mod+button5 exec --no-startup-id rofi -show window -theme /home/$USER/.config/rofi/mine.rasi

# flameshot
bindsym --release $mod+Shift+s exec flameshot gui
bindsym --release Print exec flameshot full --clipboard
