# split in horizontal orientation
bindsym $mod+i split h

# split in vertical orientation
bindsym $mod+u split v

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+b layout toggle stacking tabbed
bindsym $mod+w layout toggle split

# toggle tiling / floating
bindsym $mod+f floating toggle
