# Focus
## change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

## change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# Move
## move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# Resize
bindsym $mod+r mode "resize"

## resize window
mode "resize" {
    bindsym h resize shrink width 10 px or 10 ppt
    bindsym j resize grow height 10 px or 10 ppt
    bindsym k resize shrink height 10 px or 10 ppt
    bindsym l resize grow width 10 px or 10 ppt

    bindsym shift+h resize shrink width 30 px or 30 ppt
    bindsym shift+j resize grow height 30 px or 30 ppt
    bindsym shift+k resize shrink height 30 px or 30 ppt
    bindsym shift+l resize grow width 30 px or 30 ppt

    # back to normal: Enter or q
    bindsym Return mode "default"
    bindsym q      mode "default"
}

## modify gaps
bindsym $mod+Control+0     gaps inner current set 10
bindsym $mod+Control+plus  gaps inner current plus 5
bindsym $mod+Control+minus gaps inner current minus 5
