# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# nm-applet
exec --no-startup-id nm-applet

# Picom
exec --no-startup-id picom --config ~/.config/picom/picom.conf -b

# rime
exec --no-startup-id fcitx5

# ibus
exec --no-startup-id ibus-daemon

# display monitor
exec --no-startup-id display

# polkit
exec --no-startup-id /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id /usr/libexec/lxqt-policykit-agent

# dunst
exec --no-startup-id dunst

# greenclip
exec --no-startup-id greenclip daemon

# flameshot
exec --no-startup-id flameshot

# polybar
exec_always --no-startup-id $HOME/.config/polybar/launch.sh

# Display Wallpaper
exec_always feh --bg-fill /home/$USER/.config/i3/wallpaper.jpg
