for_window [class="Clash-verge"]        floating enable, resize set 900 600, move position center
for_window [class="dolphin"]            floating enable, resize set 900 600, move position center
for_window [class="Thunar"]             floating enable, move position center
for_window [class="org.gnome.Nautilus"] floating enable, move position center
for_window [class="gnome-text-editor"]  floating enable, move position center
for_window [class="obsidian"]           floating enable, move position center
