backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 12;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.7;

shadow-exclude = [
  "window_type = 'menu'"
];

fading = false;
fade-in-step = 0.03;
fade-out-step = 0.03;

corner-radius = 12;

inactive-opacity = 0.7;
active-opacity = 1.0;

blur:
{
  method = "dual_kawase";
  strength = 5;
}

blur-background = true;

blur-background-exclude = [
  "window_type = 'menu'"
];

opacity-rule = [
  "90:class_g = 'Alacritty'",
  "90:class_g = 'kitty'",
  "90:class_g = 'i3lock'"
];
