#!/bin/bash

COUNT=$(xrandr | grep -c " connected")

if [ "$COUNT" -eq 2 ]; then
    if [ "$(hostname)" == "laptop" ]; then
        xrandr --output eDP-1 --primary --auto
        xrandr --output HDMI-1-0 --auto --below eDP-1
        i3-msg "workspace 1; move workspace to output eDP-1"
        i3-msg "workspace 4; move workspace to output HDMI-1-0"
    else
        xrandr \
            --output DisplayPort-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal \
            --output HDMI-A-0 --mode 3840x2160 --rotate normal --pos 3840x0
        i3-msg "workspace 1; move workspace to output DisplayPort-0"
        i3-msg "workspace 4; move workspace to output HDMI-A-0"
    fi
fi
