require('config.basic')
require('config.plug')

require('plugins.codecompanion.codecompanion')
require('plugins.copilot.copilotchat')
require('plugins.copilot.copilot')
require('plugins.lang.nvim-treesitter')
require('plugins.lang.render-markdown')
require('plugins.lsp.native-lsp')
require('plugins.telescope.telescope')
require('plugins.ui.noice')
require('plugins.ui.indent')
require('plugins.ui.fold')
require('plugins.ui.diff')
require('plugins.ui.outline')
require('plugins.utils.blinkcmp')
require('plugins.utils.minipick')
require('plugins.avante.avante')
